use std::collections::BTreeMap;
use std::fmt::Write;

use crate::vault::{PREFERENCES, PROJECTS, Vault};

const HEADER: &str = "---
type: index
tags: [agent-memory]
---

# Agent memory index

Generated by petit-poucet from each note's `summary`: do not edit by hand.
";

pub fn generate(vault: &Vault) -> String {
    let mut sections: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    for note in &vault.notes {
        let section = match note.path.split('/').collect::<Vec<_>>()[..] {
            [PROJECTS, key, _] => key,
            _ => "",
        };
        let summary = note.summary().unwrap_or("(no summary)");
        sections
            .entry(section)
            .or_default()
            .push(format!("- [[{}]] — {summary}", note.path));
    }
    let mut out = HEADER.to_string();
    for (section, lines) in sections {
        let title = if section.is_empty() {
            format!("{PREFERENCES} (all repos)")
        } else {
            format!("{PROJECTS} / {section}")
        };
        write!(out, "\n## {title}\n{}\n", lines.join("\n")).unwrap();
    }
    out
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    #[test]
    fn lists_preferences_first_then_each_project() {
        let tmp = tempfile::tempdir().unwrap();
        let write = |path: &str, text: &str| {
            let path = tmp.path().join(path);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, text).unwrap();
        };
        let note = |summary: &str| {
            format!(
                "---\ntype: user\nscope: x\nsummary: {summary}\ncreated: 2026-09-24\n---\nBody\n"
            )
        };
        write("Projects/zeta/b.md", &note("zeta note"));
        write("Projects/alpha/a.md", &note("alpha note"));
        write("Preferences/p.md", &note("a preference"));
        write("Preferences/broken.md", "no frontmatter");

        assert_eq!(
            generate(&Vault::load(tmp.path()).unwrap()),
            format!(
                "{HEADER}
## Preferences (all repos)
- [[Preferences/broken]] — (no summary)
- [[Preferences/p]] — a preference

## Projects / alpha
- [[Projects/alpha/a]] — alpha note

## Projects / zeta
- [[Projects/zeta/b]] — zeta note
"
            )
        );
    }
}
