use std::collections::BTreeMap;
use std::fmt::Write;

use crate::note::Place;
use crate::vault::{PREFERENCES, PROJECTS, TOPICS, Vault};

pub const NO_SUMMARY: &str = "(no summary)";

const HEADER: &str = "---
type: index
tags: [agent-memory]
---

# Agent memory index

Generated by petit-poucet from each note's `summary`: do not edit by hand.
";

pub fn generate(vault: &Vault) -> String {
    HEADER.to_string() + &sections(vault, |_| true)
}

pub fn in_session(place: Place, project: Option<&str>) -> bool {
    place == Place::Preferences || project.is_some_and(|p| place == Place::Project(p))
}

// What an agent needs at session start: the preferences, its own project, and only the names of the topics.
pub fn for_project(vault: &Vault, project: Option<&str>) -> String {
    let mut out = sections(vault, |place| in_session(place, project));
    let mut topics: BTreeMap<&str, usize> = BTreeMap::new();
    for note in &vault.notes {
        if let Place::Topic(topic) = note.place() {
            *topics.entry(topic).or_default() += 1;
        }
    }
    if !topics.is_empty() {
        let list: Vec<String> = topics.iter().map(|(t, n)| format!("{t} ({n})")).collect();
        write!(
            out,
            "\n{TOPICS} (not loaded: memory_search covers them, memory_index with `topic` lists one): {}\n",
            list.join(", ")
        )
        .unwrap();
    }
    out
}

pub fn for_topic(vault: &Vault, topic: &str) -> String {
    sections(vault, |place| place == Place::Topic(topic))
}

fn sections(vault: &Vault, keep: impl Fn(Place) -> bool) -> String {
    let mut sections: BTreeMap<Place, Vec<String>> = BTreeMap::new();
    for note in vault.notes.iter().filter(|n| keep(n.place())) {
        let summary = note.summary().unwrap_or(NO_SUMMARY);
        sections
            .entry(note.place())
            .or_default()
            .push(format!("- [[{}]] — {summary}", note.path));
    }
    let mut out = String::new();
    for (place, lines) in sections {
        let title = match place {
            Place::Preferences => format!("{PREFERENCES} (all repos)"),
            Place::Project(key) => format!("{PROJECTS} / {key}"),
            Place::Topic(key) => format!("{TOPICS} / {key}"),
        };
        write!(out, "\n## {title}\n{}\n", lines.join("\n")).unwrap();
    }
    out
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    #[test]
    fn lists_preferences_first_then_each_project() {
        let tmp = tempfile::tempdir().unwrap();
        let write = |path: &str, text: &str| {
            let path = tmp.path().join(path);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, text).unwrap();
        };
        let note = |summary: &str| {
            format!(
                "---\ntype: user\nscope: x\nsummary: {summary}\ncreated: 2026-09-24\n---\nBody\n"
            )
        };
        write("Projects/zeta/b.md", &note("zeta note"));
        write("Projects/alpha/a.md", &note("alpha note"));
        write("Preferences/p.md", &note("a preference"));
        write("Preferences/broken.md", "no frontmatter");

        assert_eq!(
            generate(&Vault::load(tmp.path()).unwrap()),
            format!(
                "{HEADER}
## Preferences (all repos)
- [[Preferences/broken]] — (no summary)
- [[Preferences/p]] — a preference

## Projects / alpha
- [[Projects/alpha/a]] — alpha note

## Projects / zeta
- [[Projects/zeta/b]] — zeta note
"
            )
        );
    }

    #[test]
    fn project_view_keeps_preferences_and_that_project() {
        let tmp = tempfile::tempdir().unwrap();
        for path in [
            "Preferences/p.md",
            "Projects/alpha/a.md",
            "Projects/zeta/b.md",
        ] {
            let path = tmp.path().join(path);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, "x").unwrap();
        }
        let vault = Vault::load(tmp.path()).unwrap();
        let view = for_project(&vault, Some("alpha"));
        assert!(view.contains("[[Preferences/p]]") && view.contains("[[Projects/alpha/a]]"));
        assert!(!view.contains("zeta"));
        assert!(!for_project(&vault, None).contains("Projects"));
        assert!(!view.contains("Topics"), "no topics, no topic line");
    }

    #[test]
    fn topics_are_listed_in_full_in_the_file_and_by_name_at_session_start() {
        let tmp = tempfile::tempdir().unwrap();
        for path in [
            "Preferences/p.md",
            "Topics/homelab/nas.md",
            "Topics/homelab/vpn.md",
            "Topics/work-mac/proxy.md",
        ] {
            let path = tmp.path().join(path);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, "x").unwrap();
        }
        let vault = Vault::load(tmp.path()).unwrap();
        let file = generate(&vault);
        assert!(
            file.contains("\n## Topics / homelab\n- [[Topics/homelab/nas]] — (no summary)\n"),
            "{file}"
        );

        let session = for_project(&vault, None);
        assert!(!session.contains("[[Topics/"), "{session}");
        assert!(
            session.ends_with(": homelab (2), work-mac (1)\n"),
            "{session}"
        );

        let topic = for_topic(&vault, "homelab");
        assert!(
            topic.contains("[[Topics/homelab/vpn]]")
                && !topic.contains("work-mac")
                && !topic.contains("Preferences")
        );
    }
}
