use std::collections::BTreeMap;
use std::fmt::Write;

use crate::vault::{PREFERENCES, PROJECTS, Vault};

pub const NO_SUMMARY: &str = "(no summary)";

const HEADER: &str = "---
type: index
tags: [agent-memory]
---

# Agent memory index

Generated by petit-poucet from each note's `summary`: do not edit by hand.
";

pub fn generate(vault: &Vault) -> String {
    HEADER.to_string() + &sections(vault, |_| true)
}

// What an agent needs at session start: the preferences and its own project only.
pub fn for_project(vault: &Vault, project: Option<&str>) -> String {
    sections(vault, |key| key.is_none() || key == project)
}

fn sections(vault: &Vault, keep: impl Fn(Option<&str>) -> bool) -> String {
    let mut sections: BTreeMap<Option<&str>, Vec<String>> = BTreeMap::new();
    for note in vault.notes.iter().filter(|n| keep(n.project())) {
        let summary = note.summary().unwrap_or(NO_SUMMARY);
        sections
            .entry(note.project())
            .or_default()
            .push(format!("- [[{}]] — {summary}", note.path));
    }
    let mut out = String::new();
    for (project, lines) in sections {
        let title = match project {
            None => format!("{PREFERENCES} (all repos)"),
            Some(key) => format!("{PROJECTS} / {key}"),
        };
        write!(out, "\n## {title}\n{}\n", lines.join("\n")).unwrap();
    }
    out
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    #[test]
    fn lists_preferences_first_then_each_project() {
        let tmp = tempfile::tempdir().unwrap();
        let write = |path: &str, text: &str| {
            let path = tmp.path().join(path);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, text).unwrap();
        };
        let note = |summary: &str| {
            format!(
                "---\ntype: user\nscope: x\nsummary: {summary}\ncreated: 2026-09-24\n---\nBody\n"
            )
        };
        write("Projects/zeta/b.md", &note("zeta note"));
        write("Projects/alpha/a.md", &note("alpha note"));
        write("Preferences/p.md", &note("a preference"));
        write("Preferences/broken.md", "no frontmatter");

        assert_eq!(
            generate(&Vault::load(tmp.path()).unwrap()),
            format!(
                "{HEADER}
## Preferences (all repos)
- [[Preferences/broken]] — (no summary)
- [[Preferences/p]] — a preference

## Projects / alpha
- [[Projects/alpha/a]] — alpha note

## Projects / zeta
- [[Projects/zeta/b]] — zeta note
"
            )
        );
    }

    #[test]
    fn project_view_keeps_preferences_and_that_project() {
        let tmp = tempfile::tempdir().unwrap();
        for path in [
            "Preferences/p.md",
            "Projects/alpha/a.md",
            "Projects/zeta/b.md",
        ] {
            let path = tmp.path().join(path);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, "x").unwrap();
        }
        let vault = Vault::load(tmp.path()).unwrap();
        let view = for_project(&vault, Some("alpha"));
        assert!(view.contains("[[Preferences/p]]") && view.contains("[[Projects/alpha/a]]"));
        assert!(!view.contains("zeta"));
        assert!(!for_project(&vault, None).contains("Projects"));
    }
}
